//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBCR.modele
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GSB_VisiteEntities : DbContext
    {
        public GSB_VisiteEntities()
            : base("name=GSB_VisiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FAMILLE> FAMILLE { get; set; }
        public DbSet<MEDICAMENT> MEDICAMENT { get; set; }
        public DbSet<MOTIF_VISITE> MOTIF_VISITE { get; set; }
        public DbSet<OFFRIR> OFFRIR { get; set; }
        public DbSet<POSSEDER> POSSEDER { get; set; }
        public DbSet<PRATICIEN> PRATICIEN { get; set; }
        public DbSet<RAPPORT_VISITE> RAPPORT_VISITE { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<SECTEUR> SECTEUR { get; set; }
        public DbSet<SPECIALITE> SPECIALITE { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TRAVAILLER> TRAVAILLER { get; set; }
        public DbSet<TYPE_PRATICIEN> TYPE_PRATICIEN { get; set; }
        public DbSet<VISITEUR> VISITEUR { get; set; }
        public DbSet<VAFFECTATION> VAFFECTATION { get; set; }
    
        public virtual ObjectResult<Nullable<int>> addRapport(string pMat, Nullable<short> pPranum, Nullable<System.DateTime> pDatVisit, string pEtat, string pConf, string pBilan, string pMotif, string pAutre, string pNomR, string pPrenomR, string pMed1, string pMed2)
        {
            var pMatParameter = pMat != null ?
                new ObjectParameter("pMat", pMat) :
                new ObjectParameter("pMat", typeof(string));
    
            var pPranumParameter = pPranum.HasValue ?
                new ObjectParameter("pPranum", pPranum) :
                new ObjectParameter("pPranum", typeof(short));
    
            var pDatVisitParameter = pDatVisit.HasValue ?
                new ObjectParameter("pDatVisit", pDatVisit) :
                new ObjectParameter("pDatVisit", typeof(System.DateTime));
    
            var pEtatParameter = pEtat != null ?
                new ObjectParameter("pEtat", pEtat) :
                new ObjectParameter("pEtat", typeof(string));
    
            var pConfParameter = pConf != null ?
                new ObjectParameter("pConf", pConf) :
                new ObjectParameter("pConf", typeof(string));
    
            var pBilanParameter = pBilan != null ?
                new ObjectParameter("pBilan", pBilan) :
                new ObjectParameter("pBilan", typeof(string));
    
            var pMotifParameter = pMotif != null ?
                new ObjectParameter("pMotif", pMotif) :
                new ObjectParameter("pMotif", typeof(string));
    
            var pAutreParameter = pAutre != null ?
                new ObjectParameter("pAutre", pAutre) :
                new ObjectParameter("pAutre", typeof(string));
    
            var pNomRParameter = pNomR != null ?
                new ObjectParameter("pNomR", pNomR) :
                new ObjectParameter("pNomR", typeof(string));
    
            var pPrenomRParameter = pPrenomR != null ?
                new ObjectParameter("pPrenomR", pPrenomR) :
                new ObjectParameter("pPrenomR", typeof(string));
    
            var pMed1Parameter = pMed1 != null ?
                new ObjectParameter("pMed1", pMed1) :
                new ObjectParameter("pMed1", typeof(string));
    
            var pMed2Parameter = pMed2 != null ?
                new ObjectParameter("pMed2", pMed2) :
                new ObjectParameter("pMed2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("addRapport", pMatParameter, pPranumParameter, pDatVisitParameter, pEtatParameter, pConfParameter, pBilanParameter, pMotifParameter, pAutreParameter, pNomRParameter, pPrenomRParameter, pMed1Parameter, pMed2Parameter);
        }
    
        public virtual int updRapport(string pMat, Nullable<int> pNum, Nullable<short> pPranum, Nullable<System.DateTime> pDatVisit, string pEtat, string pConf, string pBilan, string pMotif, string pAutre, string pNomR, string pPrenomR, string pMed1, string pMed2)
        {
            var pMatParameter = pMat != null ?
                new ObjectParameter("pMat", pMat) :
                new ObjectParameter("pMat", typeof(string));
    
            var pNumParameter = pNum.HasValue ?
                new ObjectParameter("pNum", pNum) :
                new ObjectParameter("pNum", typeof(int));
    
            var pPranumParameter = pPranum.HasValue ?
                new ObjectParameter("pPranum", pPranum) :
                new ObjectParameter("pPranum", typeof(short));
    
            var pDatVisitParameter = pDatVisit.HasValue ?
                new ObjectParameter("pDatVisit", pDatVisit) :
                new ObjectParameter("pDatVisit", typeof(System.DateTime));
    
            var pEtatParameter = pEtat != null ?
                new ObjectParameter("pEtat", pEtat) :
                new ObjectParameter("pEtat", typeof(string));
    
            var pConfParameter = pConf != null ?
                new ObjectParameter("pConf", pConf) :
                new ObjectParameter("pConf", typeof(string));
    
            var pBilanParameter = pBilan != null ?
                new ObjectParameter("pBilan", pBilan) :
                new ObjectParameter("pBilan", typeof(string));
    
            var pMotifParameter = pMotif != null ?
                new ObjectParameter("pMotif", pMotif) :
                new ObjectParameter("pMotif", typeof(string));
    
            var pAutreParameter = pAutre != null ?
                new ObjectParameter("pAutre", pAutre) :
                new ObjectParameter("pAutre", typeof(string));
    
            var pNomRParameter = pNomR != null ?
                new ObjectParameter("pNomR", pNomR) :
                new ObjectParameter("pNomR", typeof(string));
    
            var pPrenomRParameter = pPrenomR != null ?
                new ObjectParameter("pPrenomR", pPrenomR) :
                new ObjectParameter("pPrenomR", typeof(string));
    
            var pMed1Parameter = pMed1 != null ?
                new ObjectParameter("pMed1", pMed1) :
                new ObjectParameter("pMed1", typeof(string));
    
            var pMed2Parameter = pMed2 != null ?
                new ObjectParameter("pMed2", pMed2) :
                new ObjectParameter("pMed2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updRapport", pMatParameter, pNumParameter, pPranumParameter, pDatVisitParameter, pEtatParameter, pConfParameter, pBilanParameter, pMotifParameter, pAutreParameter, pNomRParameter, pPrenomRParameter, pMed1Parameter, pMed2Parameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
