//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBCR.modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTIF_VISITE
    {
        public MOTIF_VISITE()
        {
            this.LesRapports = new HashSet<RAPPORT_VISITE>();
        }
    
        public string MOT_CODE { get; set; }
        public string MOT_LIBEL { get; set; }
    
        public virtual ICollection<RAPPORT_VISITE> LesRapports { get; set; }
    }
}
