//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBCR.modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFRIR
    {
        public string VIS_MATRICULE { get; set; }
        public int RAP_NUM { get; set; }
        public string MED_DEPOTLEGAL { get; set; }
        public Nullable<short> OFF_QTE { get; set; }
    
        public virtual MEDICAMENT LeMedicament { get; set; }
        public virtual RAPPORT_VISITE LeRapport { get; set; }
    }
}
