//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBCR.modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSSEDER
    {
        public short PRA_NUM { get; set; }
        public string SPE_CODE { get; set; }
        public string POS_DIPLOME { get; set; }
        public Nullable<float> POS_COEFPRESCRIPTION { get; set; }
    
        public virtual SPECIALITE LaSpecialite { get; set; }
        public virtual PRATICIEN LePraticien { get; set; }
    }
}
