//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBCR.modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALITE
    {
        public SPECIALITE()
        {
            this.POSSEDERs = new HashSet<POSSEDER>();
        }
    
        public string SPE_CODE { get; set; }
        public string SPE_LIBELLE { get; set; }
    
        public virtual ICollection<POSSEDER> POSSEDERs { get; set; }
    }
}
