//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBCR.modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_PRATICIEN
    {
        public TYPE_PRATICIEN()
        {
            this.LesPraticiens = new HashSet<PRATICIEN>();
        }
    
        public string TYP_CODE { get; set; }
        public string TYP_LIBELLE { get; set; }
        public string TYP_LIEU { get; set; }
    
        public virtual ICollection<PRATICIEN> LesPraticiens { get; set; }
    }
}
